version: 0.2

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: "$DOCKER_HUB_SECRET_ARN:username"
    DOCKER_HUB_PASSWORD: "$DOCKER_HUB_SECRET_ARN:password"

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - apt install -y jq
      - echo Logging into DockerHub...
      - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mvn package
      - echo Build completed on `date`
      - chmod 755 images.sh
      - ./images.sh
  post_build:
    commands:
      - docker images
      - cat orders-api-appspec.yaml
      - cat users-api-appspec.yaml
      - cat orders-api-taskdef.json
      - cat users-api-taskdef.json
artifacts:
  files:
    - orders-api-appspec.yaml
    - users-api-appspec.yaml
    - orders-api-taskdef.json
    - users-api-taskdef.json
