version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - product-orders-api/target/product-orders-api-1.0.jar
    - todos-api/target/todos-api-1.0.jar
    - users-api/target/users-api-1.0.jar