version: 0.2

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: "$DOCKER_HUB_SECRET_ARN:username"
    DOCKER_HUB_PASSWORD: "$DOCKER_HUB_SECRET_ARN:password"

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging into DockerHub...
      - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mvn package
      - echo Build completed on `date`
      - chmod 777 build-images.sh
      - ./build-images.sh
  post_build:
    commands:
      - docker images
artifacts:
  files:
    - ./orders-api/target/orders-api-1.0.jar
    - ./users-api/target/users-api-1.0.jar
    - ./appspec.yml
  discard-paths: yes
