version: '3'
services:
  users-api:
    container_name: users-api
    build:
      context: users-api
    image: smuralee/users-api:latest
    ports:
      - 9001:8001
    environment:
      - SERVER_PORT=8001
  orders-api:
    container_name: orders-api
    build:
      context: orders-api
    image: smuralee/orders-api:latest
    ports:
      - 9002:8002
    environment:
      - SERVER_PORT=8002

