version: '3'
services:
  users-api:
    container_name: users-api
    build:
      context: api/users-api
    image: smuralee/users-api:latest
    ports:
      - 9003:8003
    depends_on:
      - todos-api
      - product-orders-api
    environment:
      - SERVER_PORT=8003
      - TODOS_HOSTNAME=todos-api
      - TODOS_PORT=8002
      - ORDERS_HOSTNAME=product-orders-api
      - ORDERS_PORT=8001
  todos-api:
    container_name: todos-api
    build:
      context: api/todos-api
    image: smuralee/todos-api:latest
    ports:
      - 9002:8002
    environment:
      - SERVER_PORT=8002
  product-orders-api:
    container_name: product-orders-api
    build:
      context: api/product-orders-api
    image: smuralee/product-orders-api:latest
    ports:
      - 9001:8001
    environment:
      - SERVER_PORT=8001

