version: '3'
services:
  orders-api:
    container_name: orders-api
    build:
      context: orders-api
    image: smuralee/orders-api:latest
    ports:
      - 9001:8080
    environment:
      - SERVER_PORT=8080
  users-api:
    container_name: users-api
    build:
      context: users-api
    image: smuralee/users-api:latest
    ports:
      - 9002:8080
    environment:
      - SERVER_PORT=8080
      - ORDERS_HOST=orders-api:8080
    links:
      - "orders-api"


