spring:
  application:
    name: todos
server:
  port: 0
  servlet:
    context-path: /todos
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.smuralee: DEBUG
    org.hibernate: ERROR

app:
  features:
    secretManagement: false