INSERT INTO PRODUCT_ORDERS (ID, USER_ID, NAME, AMOUNT, CURRENCY_CODE)
VALUES (1001, 2001, 'Carpet', 12.34, 'USD');
INSERT INTO PRODUCT_ORDERS (ID, USER_ID, NAME, AMOUNT, CURRENCY_CODE)
VALUES (1002, 2001, 'Sofa', 9.30, 'USD');
INSERT INTO PRODUCT_ORDERS (ID, USER_ID, NAME, AMOUNT, CURRENCY_CODE)
VALUES (1003, 2002, 'Cooking Gloves', 8.00, 'GBP');
INSERT INTO PRODUCT_ORDERS (ID, USER_ID, NAME, AMOUNT, CURRENCY_CODE)
VALUES (1004, 2003, 'iPhone Accessory', 28.00, 'GBP');
