spring:
  application:
    name: users
server:
  port: 8080
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.smuralee: DEBUG
    org.hibernate: ERROR

app:
  features:
    secretManagement: false