spring:
  application:
    name: users-api

server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.smuralee: DEBUG
    org.hibernate: ERROR
    com.amazonaws.xray: INFO

app:
  secretManagement: false
