spring:
  application:
    name: users-api
  datasource:
    initialization-mode: always
    tomcat:
      jdbc-interceptors: com.amazonaws.xray.sql.postgres.TracingInterceptor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.smuralee: DEBUG
    org.hibernate: ERROR
    com.amazonaws.xray: INFO

app:
  rdsSecret: "dev/rds/api/users"
