INSERT INTO USERS (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, AGE)
VALUES (2001, 'Thomas', 'Neo', 'Anderson', 30);
INSERT INTO USERS (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, AGE)
VALUES (2002, 'Mrs. Maisel', NULL, NULL, 28);
INSERT INTO USERS (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, AGE)
VALUES (2003, 'Bruce', NULL, 'Wayne', 35);
